framework:
  cache:
    app: 'cache.adapter.redis'
    default_redis_provider: 'redis://127.0.0.1:6379'

    pools:
      my_cache_pool:
        adapter: cache.adapter.redis
        default_lifetime: 300
      doctrine_result_cache:
        adapter: 'cache.adapter.redis'
        provider: 'redis://127.0.0.1:6379'
        default_lifetime: 300

      doctrine_query_cache:
        adapter: 'cache.adapter.redis'
        provider: 'redis://127.0.0.1:6379'
        default_lifetime: 3600

