security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    database_users:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    # Routes internes de Symfony (profiler, assets)
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Login API
    api:
      pattern: ^/api
      stateless: true
      entry_point: jwt
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      login_throttling:
        max_attempts: 5
        interval: '10 minutes'
      jwt: ~
      refresh_jwt:
        check_path: /api/token/refresh

    main:
      lazy: true
      provider: database_users
      form_login:
        check_path: app_login
        login_path: app_login
        enable_csrf: true
        default_target_path: user_index
        username_parameter: "username"
        password_parameter: "password"
      logout:
        path: app_logout
        target: index
      entry_point: 'form_login'

  access_control:
    - { path: ^/api/(login|login/google|token/refresh), roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/_locales/admin, roles: ROLE_ADMIN }

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

when@test:
  security:
    firewalls:
      main:
        http_basic: ~
