homepage:
  path: /

api_login:
  path: /api/login

api_refresh_token:
  path: /api/token/refresh

api_google_login:
  path: /api/login/google
  controller: App\Controller\GoogleController::login

api_user:
  path: /api/user
  controller: App\Controller\UserController::index

api_add_read:
  path: /api/user/read/{id}
  controller: App\Controller\MangaController::addRead
  methods: POST

api_add_favorite:
  path: /api/user/favorite/{id}
  controller: App\Controller\MangaController::addFavorite
  methods: POST

api_remove_favorite:
  path: /api/user/favorite/{id}
  controller: App\Controller\MangaController::removeFavorite
  methods: DELETE

api_manga_favorite:
  path: /api/user/manga/favorite/page/{page}
  controller: App\Controller\UserController::mangaFavorite

api_manga_read:
  path: /api/user/manga/read/page/{page}
  controller: App\Controller\UserController::mangaRead

controllers:
  prefix: /{_locale}
  resource: ../src/Controller/
  type: attribute
  requirements:
    _locale: '%app_locales%'

kernel:
  resource: ../src/Kernel.php
  type: attribute
