homepage:
  path: /
controllers:
    prefix: /{_locale}
    resource: ../src/Controller/
    type: annotation
    requirements:
      _locale: '%app_locales%'

kernel:
    resource: ../src/Kernel.php
    type: annotation
